### ISSUE TITLE
Setext heading colorization

### ISSUE THREAD

**Issue by tom-newhall** [baincd/vscode-markdown-color-plus#4]
Hi,

Thanks for this great extension!

I like to use Setext style headings in my markdown documents,  ( i.e. 

```
Heading level 1
===========

Heading level 2 
---------------

### Heading Level 3

```

but I would like the _text_ of those sextet headings to be colorized along with the dashes or equals symbols below them. In other words, I would like them to look visually like "normal" "hashtag" headings. Right now, in my editor, in the above example, `Heading level 1` and `Heading level 2` appear as white text while  `===========` and `---------------` are blue; in contrast, all of `### Heading Level 3` is rendered as blue. 

Perhaps this is something that can be changed with a theme rather than an extension? I tried to modify this myself but the scopes for the `Heading level 1` etc., text is `
`meta.paragraph.markdown` `text.html.markdown` which targets the rest of the body text as well.

Thanks in advance

**Comment by baincd** [comment]
I found that this has been an issue in VS Code since 2016 (https://github.com/microsoft/vscode/issues/9784).  It seems the issue cannot be fixed directly in VS Code due to limitations in the TextMate grammar engine used.

I think markdown-color-plus could do this, but based on my analysis I unfortunately don't think the extension would be able to directly use the theme colors and decorations used for other markdown headers.  Meaning it will require you to configure the header color and decoration (bold, etc) for the Setext headers in the extension settings.  If you want it to match your theme you will have to figure out colors to use for those settings.

I do like this idea.  I'm considering if there should be separate set of settings for level 1 and level 2, or a single set of settings for both (I'm leaning towards separate for maximum flexibility, even if it does double the number of settings).  

I will look into this when I find some time.

**Comment by baincd** [comment]
@tom-newhall I have added support for setext-style headers in the latest version (1.6.0).  Take a look and let me know what you think.  And thank you for the great idea!
